version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: estagios
      POSTGRES_USER: estagios
      POSTGRES_PASSWORD: estagios
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data:
